import { pullHosts } from '../hosts/check';
import { initCoomeetMainWorldInject } from './coomeet-main-world-inject';
import { initDocumentVisibilitySpoof } from './document-visibility-spoof';
import { initFclcAlertSuppress, initFclcLinksGo } from '../sites/fclc';
import { initAnkergamesMainWorldInject } from '../sites/ankergames';
import { initAnygameMainWorldInject } from '../sites/anygame';
import { initApktealMainWorldInject } from '../sites/apkteal';
import { initFilecrExtractLink } from '../sites/filecr';
import { initFilecrRouteWatch } from '../sites/filecr/route-watch';
import { initFlightsimDownloadPatch } from '../sites/flightsim';
import { initShortxlinksFetchChain } from '../sites/shortxlinks';
import { initMultiup } from '../sites/multiup';
import { initLootlabsMainWorldInject } from '../sites/lootlabs';
import { initXdmoviesMainWorldInject } from '../sites/xdmovies/mediator-page';
import { initArolinksOrigin } from '../sites/arolinks';
import { initTipsguruCookieDest } from '../sites/tipsguru';
import { initExeioAdblockInject } from '../sites/exeio';
import { initFilecryptPowInject } from '../sites/filecrypt';
import { initLksfyAdblockInject } from '../sites/lksfy';
import { initRinkuFlowWatch } from '../sites/rinku';
import { initCutyGoUnlockInject, initCutyQuickRedirect } from '../sites/cuty';
import { initStorylineScormMainWorldInject } from '../sites/storyline-scorm';
import { initLink4mRedirect } from '../sites/tech8s';
import { initOceanofgamesResolve } from '../sites/oceanofgames';
import { initGapkmodResolve } from '../sites/gapkmod';
import { initDevuploadsResolve } from '../sites/devuploads';
import { initDuploadHoldNav, initDuploadResolve } from '../sites/dupload';
import { initStreamerviewerbotMainWorldInject } from '../sites/streamerviewerbot';
import { initWorkinkMainWorldInject } from '../sites/workink';
import { initVexfileMainWorldInject } from '../sites/vexfile';

initCoomeetMainWorldInject();
initDocumentVisibilitySpoof();
initFclcAlertSuppress();
initFclcLinksGo();
initAnkergamesMainWorldInject();
initAnygameMainWorldInject();
initApktealMainWorldInject();
initFilecrExtractLink();
initFilecrRouteWatch();
initFlightsimDownloadPatch();
initShortxlinksFetchChain();
initMultiup();
initLink4mRedirect();
initLootlabsMainWorldInject();
initXdmoviesMainWorldInject();
initArolinksOrigin();
initTipsguruCookieDest();
initExeioAdblockInject();
initFilecryptPowInject();
initLksfyAdblockInject();
initRinkuFlowWatch();
initCutyGoUnlockInject();
initCutyQuickRedirect();
initStorylineScormMainWorldInject();
initStreamerviewerbotMainWorldInject();
initWorkinkMainWorldInject();
initOceanofgamesResolve();
initGapkmodResolve();
initDevuploadsResolve();
initDuploadHoldNav();
initDuploadResolve();
initVexfileMainWorldInject();

chrome.runtime.onStartup.addListener(() => {
  void pullHosts();
});
