import { initCoomeetMainWorldInject } from './coomeet-main-world-inject';
import { initDocumentVisibilitySpoof } from './document-visibility-spoof';
import { initFclcAlertSuppress, initFclcLinksGo } from '../sites/fclc';
import { initAnygameMainWorldInject } from '../sites/anygame';
import { initApktealMainWorldInject } from '../sites/apkteal';
import { initFilecrExtractLink } from '../sites/filecr';
import { initFilecrRouteWatch } from '../sites/filecr/route-watch';
import { initFlightsimDownloadPatch } from '../sites/flightsim';
import { initShortxlinksFetchChain } from '../sites/shortxlinks';
import { initMultiup } from '../sites/multiup';
import { initLootlabsMainWorldInject } from '../sites/lootlabs';
import { initXdmoviesMainWorldInject } from '../sites/xdmovies/mediator-page';
import { initTipsguruCookieDest } from '../sites/tipsguru';
import { initExeioAdblockInject } from '../sites/exeio';
import { initFilecryptPowInject } from '../sites/filecrypt';
import { initLksfyAdblockInject } from '../sites/lksfy';
import { initCutyAdblockInject } from '../sites/cuty';
import { initRinkuPageHooksInject } from '../sites/rinku';
import { initStorylineScormMainWorldInject } from '../sites/storyline-scorm';
import { initLink4mRedirect } from '../sites/tech8s';

initCoomeetMainWorldInject();
initDocumentVisibilitySpoof();
initFclcAlertSuppress();
initFclcLinksGo();
initAnygameMainWorldInject();
initApktealMainWorldInject();
initFilecrExtractLink();
initFilecrRouteWatch();
initFlightsimDownloadPatch();
initShortxlinksFetchChain();
initMultiup();
initLink4mRedirect();
initLootlabsMainWorldInject();
initXdmoviesMainWorldInject();
initTipsguruCookieDest();
initExeioAdblockInject();
initFilecryptPowInject();
initLksfyAdblockInject();
initCutyAdblockInject();
initRinkuPageHooksInject();
initStorylineScormMainWorldInject();
